sudo: required
services:
    - docker

before_install:
    - docker build -t peterzara/docker-react -f Dockerfile.dev .

script:
    - docker run peterzara/docker-react npm run test -- --coverage
    