version: '3'
services: 
    web:
        build: 
            context: .  # find dockerfile in this dic
            dockerfile: Dockerfile.dev  # specify the dockerfile name
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules  # -v /app/node_modules
            - .:/app  # -v $(pwd):/app
    tests:  # 2nd container
        build: 
            context: .  # find dockerfile in this dic
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules  # -v /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]